---
title: "R Notebook"
output: html_notebook
---

```{r}
library(DESeq2)
library(ggplot2)
library(ComplexHeatmap)
library(org.Hs.eg.db) # library(org.Mm.eg.db) for mouse
library(EnhancedVolcano)
library(clusterProfiler)
library(AnnotationDbi)
```

```{r}
counts <- read.delim("C:/Bulk_RNA_Seq_Analysis/data/count.out", header = TRUE, row.names = 1)
```

```{r}
counts <- counts[which(rowSums(counts) > 0),]
counts
```

```{r}
condition <-  factor(c("C","S","C","S","C","S","C","S"))
coldata <- data.frame(row.names = colnames(counts), condition)
coldata
```

```{r}
dds <- DESeqDataSetFromMatrix(countData = counts, colData = coldata, design = ~condition)
dds <- DESeq(dds)
vsdata <- vst(dds, blind = FALSE)
```

```{r}
pca_plot <- plotPCA(vsdata, intgroup="condition")+
  theme_grey()
print(pca_plot)  

ggsave("C:/Bulk_RNA_Seq_Analysis/images/pca_plot.png", plot = pca_plot)

```

```{r}
res <- results(dds, contrast = c("condition", "S", "C"))
res
```

```{r}
res <- na.omit(res)
res.df <- as.data.frame(res)
res.df
```
```{r}
res.df$symbol <- mapIds(org.Hs.eg.db, keys = rownames(res.df), keytype = "ENSEMBL", column = "SYMBOL")
res.df <- res.df[!is.na(res.df$symbol),]
res.df

write.csv(res.df, "C:/Bulk_RNA_Seq_Analysis/data/deseq_out.csv", row.names = TRUE)
```

```{r}
# EnhancedVolcano(res.df, x = 'log2FoldChange', y = 'padj', lab = res.df$symbol)
enhanced_volcano <- EnhancedVolcano(res.df, x = 'log2FoldChange', y = 'padj', lab = res.df$symbol,
                  pCutoff = 0.05, FCcutoff = 2)
print(enhanced_volcano)

ggsave("C:/Bulk_RNA_Seq_Analysis/images/enhanced_volcano.png", plot = enhanced_volcano)
```

```{r}
res.df$expression <- "NOT"
res.df$expression[res.df$padj < 0.05 & res.df$log2FoldChange > 1] <- "UP"
res.df$expression[res.df$padj < 0.05 & res.df$log2FoldChange < -1] <- "DOWN"

ggplot_volcano <- ggplot(data = res.df, aes(x = log2FoldChange, y = -log10(padj), col = expression)) +
  geom_vline(xintercept = c(-1, 1), col = "gray", linetype = 'dashed') +
  geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') +
  geom_point(size = 2) +
  scale_color_manual(values = c("#3498DB", "grey", "#E74C3C"), 
                     labels = c("Downregulated", "Not significant", "Upregulated")) +
  theme_classic()

print(ggplot_volcano)

ggsave("C:/Bulk_RNA_Seq_Analysis/images/ggplot_volcano.png", plot = ggplot_volcano)
```
```{r}
sigs.df <- res.df[res.df$padj < 0.05,]
sigs.df <- sigs.df[(sigs.df$baseMean > 100) & (abs(sigs.df$log2FoldChange) > 1),]
sigs.df

```


```{r}
write.csv(sigs.df, "C:/Bulk_RNA_Seq_Analysis/data/sig_genes.csv", row.names = TRUE)
```

```{r}
mat <- counts(dds, normalized=T)[rownames(sigs.df),]
mat.z <- t(apply(mat, 1, scale))
colnames(mat.z) <- rownames(coldata)
```

```{r}
diff_heatmap <- Heatmap(mat.z, cluster_rows = T, cluster_columns = T, column_labels = colnames(mat.z),
        name = "Z-score", row_labels = sigs.df[rownames(mat.z),]$symbol)
print(diff_heatmap)

```

```{r}
sig_genes.df <- res.df[(res.df$padj < 0.05) & (abs(res.df$log2FoldChange) > 0.5),]
genes_to_test <- rownames(sig_genes.df) # also we can use gene symbols
genes_to_test
```

```{r}
go <- enrichGO(gene = genes_to_test, OrgDb = "org.Hs.eg.db", keyType = "ENSEMBL",
               ont = "BP")

# use SYMBOL if we have gene symbols instead of ENSEMBl IDs
```

```{r}
as.data.frame(go)
```

```{r}
go_bar <- barplot(go, showCategory = 10, color = "p.adjust") +
   theme_classic() +
  scale_fill_gradient(low = "lightblue", high = "dodgerblue") 

print(go_bar)
ggsave("C:/Bulk_RNA_Seq_Analysis/images/go_bar.png", plot = go_bar)

```

```{r}
res_filtered <- res.df[res.df$padj < 0.05,]
res_ordered <- res_filtered[order(-res_filtered$stat),] # - means desc 
gene_list <- res_ordered$stat
names(gene_list) <- rownames(res_ordered)
head(gene_list)

```

```{r}
gsea <- gseGO(gene_list,
              ont = "BP",
              keyType = "ENSEMBL",
              OrgDb = "org.Hs.eg.db",
              eps = 1e-300) # more precise calculations, but can be slightly slower.
```

```{r}
as.data.frame(gsea)
```
```{r}
enrich_score<- gseaplot(gsea, by = "all", title = gsea$Description[10], geneSetID = 10)
print(enrich_score)
```


```{r}
gsea_dot <- dotplot(gsea, showCategory = 10, split = ".sign") + facet_grid(.~.sign)
print(gsea_dot)

ggsave("C:/Bulk_RNA_Seq_Analysis/images/gsea_dot.png", plot = gsea_dot)
```



